### ISSUE TITLE
[DB] mssql mdf파일의 접근성이 떨어집니다.

### ISSUE THREAD

**Issue by hihiroo** [CLASSOM/Classom#7]
mdf파일을 데이터베이스로 복원하는 과정이 너무 복잡하고 윈도우에서밖에 서버를 못돌린다는 점에서 접근성이 떨어지는 것 같습니다.

mssql에서 mysql로 변경하는 것이 좋을 것 같습니다.

**Comment by kim-dong-woo** [comment]
mysql로 변환 했습니다.

**Comment by hihiroo** [comment]
확인했습니다. 감사합니당
