### ISSUE TITLE
[DB] card_data 형식을 통일해주세요

### ISSUE THREAD

**Issue by hihiroo** [CLASSOM/Classom#8]
card_data 엑셀 파일을 보면 어떤 것은 할인율 단위가 %이고 어떤 것은 (포인트), (캐쉬백), 원 이렇게 통일이 안되어 있는데 %랑 원으로 통일해주세요.
포인트랑 캐쉬백을 나누는 의미가 없는 것 같아요.

그리고 카테고리가 겹치는 경우는 가장 큰 할인율만 적용해주세요.
예를 들어 편의점 같은 경우 CU, GS, 미니스톱 등이 있으면 셋 중에 가장 큰 할인율을 써주시면 감사하겠습니다. 
각 지점별 소비액을 가지고 계산하는게 아니라 카테고리별 소비액에 할인율을 적용하는거라 지점을 나누는게 의미가 없습니다.

**Comment by kim-dong-woo** [comment]
확인했습니다
